version: "3.8"

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-angular
    ports:
      - "4201:4200"
    command: >
      sh -c "http-server /app/dist/apps/angular-app-name -p 4200"

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-nestjs
    ports:
      - "3000:3000"
    command: >
      sh -c "node /app/dist/apps/nestjs-app-name/main.js"

